name: CI workflow

on: [push, pull_request]

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  ansible-syntax-check:
    name: Ansible syntax check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Python
        uses: actions/setup-python@v2
      - name: Install Ansible
        run: pip install ansible
      - name: Create ansible.cfg with correct roles_path
        run: printf '[defaults]\nroles_path=../' >ansible.cfg
      - name: Ansible role syntax check
        run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  vale:
    name: Run Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@v1.3.0
        with:
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [pre-commit, ansible-syntax-check, vale]
    if: ${{ needs.pre-commit.result == 'success' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - name: Release
        run: npx semantic-release
